# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - git submodule init 
      - git submodule update
      - wasm-pack build --target web
      - pnpm install
      - pnpm run build
