# https://taskfile.dev

version: '3'

vars:
  WEBROOT: "./www"

tasks:
  default:
    cmds:
      - mkdir -p {{.WEBROOT}}
      - rm -rf {{.WEBROOT}}/*
      - mkdir -p {{.WEBROOT}}/book
      - rm -rf book/book/*

      - mdbook build book -d book/book
      - wasm-pack build --target web

      - cp -R book/book/book/* {{.WEBROOT}}/book
      - cp -R static/* {{.WEBROOT}}/
      - cp pkg/*.js {{.WEBROOT}}
      - cp pkg/*.wasm {{.WEBROOT}}
