# https://taskfile.dev

version: "3"

tasks:
  book:
    dir: ./book
    cmds:
      - mdbook build

  clean:
    cmds:
      - mkdir -p dist/book
      - rm -rf dist/book/**

  pack:
    cmds:
      - wasm-pack build --target web
    generates:
      - pkg/**
      - target/**
    sources:
      - Cargo.toml
      - Cargo.lock
      - src/**

  default:
    deps: [clean, book, pack]
    cmds:
      - pnpm install
      - pnpm run build
  
  dev:
    deps: [clean, book, pack]
    cmds:
      - pnpm install
      - pnpm run start